version: '2.1'
services:
  search:
    build:
      context: .
      dockerfile: dockerfile.dev
    command: yarn test:e2e
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    depends_on: 
      es:
        condition: service_healthy

  es:
    build:
      context: .
      dockerfile: es.dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10

volumes:
  esdata1:
    driver: local
