version: '2.2'
services:
  search:
    build: .
    command: yarn start:dev
    ports:
      - 5000:3000
    volumes:
      - ./:/usr/src/app
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  esdata1:
    driver: local
